### ISSUE TITLE
Triggering errors on form submit?!

### ISSUE THREAD

**Issue by MetalNose** [PascaleBeier/bootstrap-validate#43]
Hello, 
first of all thanks a lot for this library, it has been a lot of help .. but i'm having this issue where i want to trigger input errors on submit and prevent submitting?
I tried calling `bootstrapValidate` inside ` $('#myForm').submit(function (event){}` but it seemed that it's not triggering the errors only making the function start the validations!
Anything that I'm missing ?

best regards !

**Comment by PascaleBeier** [comment]
Hey,

thanks for reaching out! For this functionality I advise you to use https://github.com/jquery-validation/jquery-validation, since I'm not working on bootstrap-validate in the near future (or, ever, but who knows)

**Comment by dominicklee** [comment]
@MetalNose  If you are still looking for a solution for this, you can do the following:

1. Give your form an ID so that you can refer to it in Javascript.
2. Then write `event.preventDefault()` so that the form won't be submitted when the user clicks submit.
3. Write a new function called `validateForm()` that is supposed to submit the form once it's valid.
4. Include jQuery in your HTML. You will need it to find "form errors".

**Let's put this all together:** 

Here is an example of your form tag:
```html
<form method="POST" id="formSignup" onsubmit="event.preventDefault(); validateForm();">
</form>
```

Add this code before your `</body>` tag:
```html
<script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
<script>
	function validateForm()
	{
		//Find the number of form errors shown
		var numInvalid = $( "#formSignup" ).find( ".invalid-feedback:not(:hidden)" ).length;

		if (numInvalid == 0) {
			//No errors, submit form
			document.getElementById("formSignup").submit();	//All is good. Submit form.
		}
		else {
			//Errors found, do not submit
		}
	}
</script>
```

I hope this helps anyone who still wants to use this wonderful library, without waiting for the new version.
