### ISSUE TITLE
Validation runs before submit

### ISSUE THREAD

**Issue by Harishan15** [PascaleBeier/bootstrap-validate#52]
It is better to be as Validating after clicked the submit button.
Because for an example, 
In email validation, the validation message comes when I started to typing. It's feels not good while typing first.
May be the user going to do the thing calmly, then the Red colored messages comes in he maybe feels scared.

My request is, the function should work after click the submit.
I manually tried many times, since I started web development recently it's bit hard to do.

**Comment by PascaleBeier** [comment]
Hey there,

this library is not actively developed aside from individual quotes.

**Comment by dominicklee** [comment]
@Harishan15 If you are still looking for a solution for this, you can do the following:

1. Give your form an ID so that you can refer to it in Javascript.
2. Then write `event.preventDefault()` so that the form won't be submitted when the user clicks submit.
3. Write a new function called `validateForm()` that is supposed to submit the form once it's valid.
4. Move your `bootstrapValidate` code inside `validateForm()`, which would only be called when user attempts to submit the form.
5. Include jQuery in your HTML. You will need it to find "form errors".

**Let's put this all together:** 

Here is an example of your form tag:
```html
<form method="POST" id="formSignup" onsubmit="event.preventDefault(); validateForm();">
</form>
```

Add this code before your `</body>` tag:
```html
<script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
<script>
	function validateForm()
	{
		//Validate email
		bootstrapValidate('#email', 'email:Enter a valid email!|required:Please fill out this field!');
		//..put your other validations here

		//Find the number of form errors shown
		var numInvalid = $( "#formSignup" ).find( ".invalid-feedback:not(:hidden)" ).length;

		if (numInvalid == 0) {
			//No errors, submit form
			document.getElementById("formSignup").submit();	//All is good. Submit form.
		}
		else {
			//Errors found, do not submit
		}
	}
</script>
```

I hope this helps anyone who still wants to use this wonderful library, without waiting for the new version.
